commit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -320,7 +320,7 @@ jobs:
             cd frontend
             npm install
             npm run build
-            aws s3 cp --recursive ./dist/ s3://udapeople-ra1k061yhdkclt198 --acl public-read
+            aws s3 cp --recursive ./dist/ s3://udapeople-${CIRCLE_WORKFLOW_ID} --acl public-read
            
             
       - destroy-environment:
@@ -386,39 +386,55 @@ jobs:
 
       # Here's where you will add some code to rollback on failure  
 
-#  smoke-test:
-#    docker:
-#     - image: python:3.7-alpine3.11
-#      # Lightweight Docker image 
-#
-#    steps:
-#      - run:
-#          name: Install dependencies ssh and git and aws cli
-#          command: |
-#            apk add --update openssh-client #Insatll ssh
-#            apk add --update git #Insatll git
-#            apk add --update tar gzip curl nodejs tree
-#            apk add --update npm
-#            pip install awscli # install aws cli
-#      # Checkout code from git
-#      - checkout
-#      - attach_workspace:
-#          at: ~/
-#          
-#      - run:
-#          name: Get backend url fro back end smoke test
-#          command: |
-#            BACKEND_IP=`cat ~/project/.circleci/ansible/inventory.txt|tail -1`
-#            export API_URL="http://${BACKEND_IP}:3030"
-#            echo "${API_URL}"
-#      - run:
-#          name: Backend smoke test.
-#          command: |
-#            # your code here
-#      - run:
-#          name: Frontend smoke test.
-#          command: |
+  smoke-test:
+    docker:
+     - image: python:3.7-alpine3.11
+      # Lightweight Docker image 
+
+    steps:
+      - run:
+          name: Install dependencies ssh and git and aws cli
+          command: |
+            apk add --update openssh-client #Insatll ssh
+            apk add --update git #Insatll git
+            apk add --update tar gzip curl nodejs tree
+            apk add --update npm
+            pip install awscli # install aws cli
+      # Checkout code from git
+      - checkout
+      - attach_workspace:
+          at: ~/
+          
+      - run:
+          name: Get backend url for back end smoke test
+          command: |
+            BACKEND_IP=`cat ~/project/.circleci/ansible/inventory.txt|tail -1`
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+      - run:
+          name: Backend smoke test.
+          command: |
+            curl -ivs ${API_URL}/api/status  > /dev/null 2>&1
+            if [ $? -eq 0 ]
+                then
+                    echo "backend smoke test passed"
+                    retrurn 0
+                else
+                    echo "backend smoke test failed"
+                    return 1
+            
+      - run:
+          name: Frontend smoke test.
+          command: |
             # your code here
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-us-east-1.amazonaws.com"
+            echo Frontend_URL: ${URL}
+            if curl -s ${URL} | grep "Welcome"
+            then
+              return 0
+            else
+              return 1
+            fi
       # Here's where you will add some code to rollback on failure  
 #
 #  cloudfront-update:
@@ -482,8 +498,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-#      - smoke-test:
-#          requires: [deploy-backend, deploy-frontend]
+      - smoke-test:
+         requires: [deploy-backend, deploy-frontend]
 #      - cloudfront-update:
 #          requires: [smoke-test]
 #      - cleanup:
